steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/healthcare-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/healthcare-frontend:latest'
      - '.'
    timeout: '1200s'

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/healthcare-frontend:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'healthcare-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/healthcare-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'

timeout: '1200s'
EOF < /dev/null